### ISSUE TITLE
Requesting to increase the status time limit for videos to 60 Seconds

### ISSUE THREAD

**Issue by BharathGanesan** [RanjithGanesan/WhatsUp-Development#4]
Dear Ranjith.G,

I would be great if you increase the status time limit for videos to 60 Seconds

**Comment by RanjithGanesan** [comment]
Dear Bharath.G, 

Thanks for suggesting the feature will add and let you know

**Comment by RanjithGanesan** [comment]
Dear Bharath.G,

Thanks for your valuable suggestion. This feature will make our product greate
